# Generated by Django 3.1.5 on 2021-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='services',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='social_link',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Social_Link',
        ),
    ]
