# Generated by Django 3.1.3 on 2021-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210223_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_blog',
            field=models.CharField(choices=[('premium', 'Premium'), ('Free', 'Free')], default='Free', max_length=10),
        ),
    ]
